name: 'build'
on:
  push:
    branches:
      - master
jobs:
  build:
    name: 'build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - run: make package
      - run: make publish
